branch = master
buildTime = 1773851598574
commitId = 93e4e1e32f0a93217c4111ec340e40d13c76df01
coreVersion = 1.4.0
default_language = en_us
group = icu.takeneko
impl_platform = Telegram
supported_languages = zh_cn,en_us
